# Generated by Django 3.1.1 on 2020-10-25 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MiddleName', models.CharField(blank=True, max_length=50, null=True)),
                ('createdfor', models.CharField(choices=[('Self', 'Self'), ('Relative', 'Relative')], max_length=20, null=True)),
                ('occupation', models.CharField(max_length=30, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('dateofbirth', models.DateField()),
                ('religion', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parents_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=200, null=True)),
                ('mothers_name', models.CharField(max_length=200, null=True)),
                ('fathers_phn', models.CharField(blank=True, max_length=20, null=True)),
                ('mothers_phn', models.CharField(blank=True, max_length=20, null=True)),
                ('fathers_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('mothers_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
