# Generated by Django 3.1.1 on 2020-10-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0002_auto_20201027_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='username'),
        ),
    ]
