# Generated by Django 3.1.1 on 2020-10-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0004_parents_details_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='FirstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='LastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='profie_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
