# Generated by Django 3.1.1 on 2020-10-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0005_auto_20201029_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
    ]
