# Generated by Django 3.1.1 on 2020-10-29 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0006_auto_20201029_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='profie_pic',
            new_name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='LastName',
        ),
        migrations.AlterField(
            model_name='user_details',
            name='dateofbirth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
