# Generated by Django 3.1.1 on 2020-10-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0007_auto_20201029_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='LastName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
