# Generated by Django 3.1.1 on 2020-10-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0010_auto_20201029_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_pic',
            field=models.ImageField(blank=True, default='registered_user/images/defaultpic.png', null=True, upload_to=''),
        ),
    ]
