# Generated by Django 3.1.1 on 2020-10-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0013_auto_20201031_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultpic.png', null=True, upload_to='images/'),
        ),
    ]
