# Generated by Django 3.1.1 on 2020-10-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0014_auto_20201031_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultpic.png', null=True, upload_to='C:\\Users\\Anshuman\\Desktop\\Django\\projects\\hastaganthi\\static/registered_user/images'),
        ),
    ]
