# Generated by Django 3.1.1 on 2020-11-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0016_auto_20201031_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultpic.png', null=True, upload_to='images'),
        ),
    ]
