# Generated by Django 3.1.1 on 2020-11-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0019_auto_20201101_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultpic.png', null=True, upload_to='users/'),
        ),
    ]
