# Generated by Django 3.1.1 on 2020-11-02 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0020_auto_20201101_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='profile_pic',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('imagefile', models.FileField(blank=True, default='images/default_pic.png', null=True, upload_to='images/', verbose_name='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
