# Generated by Django 3.1.1 on 2020-11-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0021_auto_20201102_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagefile',
            field=models.FileField(blank=True, default='default_pic.png', null=True, upload_to='images/', verbose_name=''),
        ),
    ]
