# Generated by Django 3.1.1 on 2020-11-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0022_auto_20201103_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=20, null=True)),
                ('membership_start_data', models.DateField(blank=True, null=True)),
                ('membership_end_data', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
