# Generated by Django 3.1.1 on 2020-11-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0023_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=20, null=True),
        ),
    ]
