# Generated by Django 3.1.1 on 2020-11-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0026_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='userid',
            new_name='interesteduser',
        ),
    ]
