# Generated by Django 3.1.1 on 2020-11-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0027_auto_20201110_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
