# Generated by Django 3.1.1 on 2020-11-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0029_interest_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='caste',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='salary',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
