# Generated by Django 3.1.1 on 2020-11-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0030_auto_20201119_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
