# Generated by Django 3.1.1 on 2020-12-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0031_auto_20201119_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minAge', models.IntegerField(null=True)),
                ('maxAge', models.IntegerField(null=True)),
                ('minSalary', models.IntegerField(null=True)),
                ('caste', models.CharField(max_length=200, null=True)),
                ('religion', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
