# Generated by Django 3.1.1 on 2020-12-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registered_user', '0033_preference_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='caste',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='religion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
