# Generated by Django 3.1.1 on 2020-10-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_registered_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_test',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
